# Generated by Django 5.2.6 on 2025-09-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_role', models.CharField(choices=[('chair', 'Chair'), ('co-chair', 'Co-Chair'), ('member', 'Member')], default='chair', max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='ConferenceApp.conference')),
            ],
        ),
    ]
